In [31]:
import pandas as pd

In [32]:
df = pd.read_table('https://github.com/prasertcbs/basic-dataset/raw/master/gapminder.tsv')
df

          country  year continent  lifeExp       pop    gdpPercap
0     Afghanistan  1952      Asia   28.801   8425333   779.445314
1     Afghanistan  1957      Asia   30.332   9240934   820.853030
2     Afghanistan  1962      Asia   31.997  10267083   853.100710
3     Afghanistan  1967      Asia   34.020  11537966   836.197138
4     Afghanistan  1972      Asia   36.088  13079460   739.981106
5     Afghanistan  1977      Asia   38.438  14880372   786.113360
6     Afghanistan  1982      Asia   39.854  12881816   978.011439
7     Afghanistan  1987      Asia   40.822  13867957   852.395945
8     Afghanistan  1992      Asia   41.674  16317921   649.341395
9     Afghanistan  1997      Asia   41.763  22227415   635.341351
10    Afghanistan  2002      Asia   42.129  25268405   726.734055
11    Afghanistan  2007      Asia   43.828  31889923   974.580338
12        Albania  1952    Europe   55.230   1282697  1601.056136
13        Albania  1957    Europe   59.280   1476505  1942.284244
14        Albania  1962    Europe   64.820   1728137  2312.888958
15        Albania  1967    Europe   66.220   1984060  2760.196931
16        Albania  1972    Europe   67.690   2263554  3313.422188
17        Albania  1977    Europe   68.930   2509048  3533.003910
18        Albania  1982    Europe   70.420   2780097  3630.880722
19        Albania  1987    Europe   72.000   3075321  3738.932735
20        Albania  1992    Europe   71.581   3326498  2497.437901
21        Albania  1997    Europe   72.950   3428038  3193.054604
22        Albania  2002    Europe   75.651   3508512  4604.211737
23        Albania  2007    Europe   76.423   3600523  5937.029526
24        Algeria  1952    Africa   43.077   9279525  2449.008185
25        Algeria  1957    Africa   45.685  10270856  3013.976023
26        Algeria  1962    Africa   48.303  11000948  2550.816880
27        Algeria  1967    Africa   51.407  12760499  3246.991771
28        Algeria  1972    Africa   54.518  14760787  4182.663766
29        Algeria  1977    Africa   58.014  17152804  4910.416756
...           ...   ...       ...      ...       ...          ...
1674  Yemen, Rep.  1982      Asia   49.113   9657618  1977.557010
1675  Yemen, Rep.  1987      Asia   52.922  11219340  1971.741538
1676  Yemen, Rep.  1992      Asia   55.599  13367997  1879.496673
1677  Yemen, Rep.  1997      Asia   58.020  15826497  2117.484526
1678  Yemen, Rep.  2002      Asia   60.308  18701257  2234.820827
1679  Yemen, Rep.  2007      Asia   62.698  22211743  2280.769906
1680       Zambia  1952    Africa   42.038   2672000  1147.388831
1681       Zambia  1957    Africa   44.077   3016000  1311.956766
1682       Zambia  1962    Africa   46.023   3421000  1452.725766
1683       Zambia  1967    Africa   47.768   3900000  1777.077318
1684       Zambia  1972    Africa   50.107   4506497  1773.498265
1685       Zambia  1977    Africa   51.386   5216550  1588.688299
1686       Zambia  1982    Africa   51.821   6100407  1408.678565
1687       Zambia  1987    Africa   50.821   7272406  1213.315116
1688       Zambia  1992    Africa   46.100   8381163  1210.884633
1689       Zambia  1997    Africa   40.238   9417789  1071.353818
1690       Zambia  2002    Africa   39.193  10595811  1071.613938
1691       Zambia  2007    Africa   42.384  11746035  1271.211593
1692     Zimbabwe  1952    Africa   48.451   3080907   406.884115
1693     Zimbabwe  1957    Africa   50.469   3646340   518.764268
1694     Zimbabwe  1962    Africa   52.358   4277736   527.272182
1695     Zimbabwe  1967    Africa   53.995   4995432   569.795071
1696     Zimbabwe  1972    Africa   55.635   5861135   799.362176
1697     Zimbabwe  1977    Africa   57.674   6642107   685.587682
1698     Zimbabwe  1982    Africa   60.363   7636524   788.855041
1699     Zimbabwe  1987    Africa   62.351   9216418   706.157306
1700     Zimbabwe  1992    Africa   60.377  10704340   693.420786
1701     Zimbabwe  1997    Africa   46.809  11404948   792.449960
1702     Zimbabwe  2002    Africa   39.989  11926563   672.038623
1703     Zimbabwe  2007    Africa   43.487  12311143   469.709298

[1704 rows x 6 columns]

In [33]:
df = pd.read_table('https://github.com/prasertcbs/basic-dataset/raw/master/gapminder.tsv', index_col=['country', 'year'])
df

                 continent  lifeExp       pop    gdpPercap
country     year
Afghanistan 1952      Asia   28.801   8425333   779.445314
            1957      Asia   30.332   9240934   820.853030
            1962      Asia   31.997  10267083   853.100710
            1967      Asia   34.020  11537966   836.197138
            1972      Asia   36.088  13079460   739.981106
            1977      Asia   38.438  14880372   786.113360
            1982      Asia   39.854  12881816   978.011439
            1987      Asia   40.822  13867957   852.395945
            1992      Asia   41.674  16317921   649.341395
            1997      Asia   41.763  22227415   635.341351
            2002      Asia   42.129  25268405   726.734055
            2007      Asia   43.828  31889923   974.580338
Albania     1952    Europe   55.230   1282697  1601.056136
            1957    Europe   59.280   1476505  1942.284244
            1962    Europe   64.820   1728137  2312.888958
            1967    Europe   66.220   1984060  2760.196931
            1972    Europe   67.690   2263554  3313.422188
            1977    Europe   68.930   2509048  3533.003910
            1982    Europe   70.420   2780097  3630.880722
            1987    Europe   72.000   3075321  3738.932735
            1992    Europe   71.581   3326498  2497.437901
            1997    Europe   72.950   3428038  3193.054604
            2002    Europe   75.651   3508512  4604.211737
            2007    Europe   76.423   3600523  5937.029526
Algeria     1952    Africa   43.077   9279525  2449.008185
            1957    Africa   45.685  10270856  3013.976023
            1962    Africa   48.303  11000948  2550.816880
            1967    Africa   51.407  12760499  3246.991771
            1972    Africa   54.518  14760787  4182.663766
            1977    Africa   58.014  17152804  4910.416756
...                    ...      ...       ...          ...
Yemen, Rep. 1982      Asia   49.113   9657618  1977.557010
            1987      Asia   52.922  11219340  1971.741538
            1992      Asia   55.599  13367997  1879.496673
            1997      Asia   58.020  15826497  2117.484526
            2002      Asia   60.308  18701257  2234.820827
            2007      Asia   62.698  22211743  2280.769906
Zambia      1952    Africa   42.038   2672000  1147.388831
            1957    Africa   44.077   3016000  1311.956766
            1962    Africa   46.023   3421000  1452.725766
            1967    Africa   47.768   3900000  1777.077318
            1972    Africa   50.107   4506497  1773.498265
            1977    Africa   51.386   5216550  1588.688299
            1982    Africa   51.821   6100407  1408.678565
            1987    Africa   50.821   7272406  1213.315116
            1992    Africa   46.100   8381163  1210.884633
            1997    Africa   40.238   9417789  1071.353818
            2002    Africa   39.193  10595811  1071.613938
            2007    Africa   42.384  11746035  1271.211593
Zimbabwe    1952    Africa   48.451   3080907   406.884115
            1957    Africa   50.469   3646340   518.764268
            1962    Africa   52.358   4277736   527.272182
            1967    Africa   53.995   4995432   569.795071
            1972    Africa   55.635   5861135   799.362176
            1977    Africa   57.674   6642107   685.587682
            1982    Africa   60.363   7636524   788.855041
            1987    Africa   62.351   9216418   706.157306
            1992    Africa   60.377  10704340   693.420786
            1997    Africa   46.809  11404948   792.449960
            2002    Africa   39.989  11926563   672.038623
            2007    Africa   43.487  12311143   469.709298

[1704 rows x 4 columns]

In [34]:
df = pd.read_table('https://github.com/prasertcbs/basic-dataset/raw/master/gapminder.tsv', index_col=['year', 'country'])
df

                 continent  lifeExp       pop    gdpPercap
year country
1952 Afghanistan      Asia   28.801   8425333   779.445314
1957 Afghanistan      Asia   30.332   9240934   820.853030
1962 Afghanistan      Asia   31.997  10267083   853.100710
1967 Afghanistan      Asia   34.020  11537966   836.197138
1972 Afghanistan      Asia   36.088  13079460   739.981106
1977 Afghanistan      Asia   38.438  14880372   786.113360
1982 Afghanistan      Asia   39.854  12881816   978.011439
1987 Afghanistan      Asia   40.822  13867957   852.395945
1992 Afghanistan      Asia   41.674  16317921   649.341395
1997 Afghanistan      Asia   41.763  22227415   635.341351
2002 Afghanistan      Asia   42.129  25268405   726.734055
2007 Afghanistan      Asia   43.828  31889923   974.580338
1952 Albania        Europe   55.230   1282697  1601.056136
1957 Albania        Europe   59.280   1476505  1942.284244
1962 Albania        Europe   64.820   1728137  2312.888958
1967 Albania        Europe   66.220   1984060  2760.196931
1972 Albania        Europe   67.690   2263554  3313.422188
1977 Albania        Europe   68.930   2509048  3533.003910
1982 Albania        Europe   70.420   2780097  3630.880722
1987 Albania        Europe   72.000   3075321  3738.932735
1992 Albania        Europe   71.581   3326498  2497.437901
1997 Albania        Europe   72.950   3428038  3193.054604
2002 Albania        Europe   75.651   3508512  4604.211737
2007 Albania        Europe   76.423   3600523  5937.029526
1952 Algeria        Africa   43.077   9279525  2449.008185
1957 Algeria        Africa   45.685  10270856  3013.976023
1962 Algeria        Africa   48.303  11000948  2550.816880
1967 Algeria        Africa   51.407  12760499  3246.991771
1972 Algeria        Africa   54.518  14760787  4182.663766
1977 Algeria        Africa   58.014  17152804  4910.416756
...                    ...      ...       ...          ...
1982 Yemen, Rep.      Asia   49.113   9657618  1977.557010
1987 Yemen, Rep.      Asia   52.922  11219340  1971.741538
1992 Yemen, Rep.      Asia   55.599  13367997  1879.496673
1997 Yemen, Rep.      Asia   58.020  15826497  2117.484526
2002 Yemen, Rep.      Asia   60.308  18701257  2234.820827
2007 Yemen, Rep.      Asia   62.698  22211743  2280.769906
1952 Zambia         Africa   42.038   2672000  1147.388831
1957 Zambia         Africa   44.077   3016000  1311.956766
1962 Zambia         Africa   46.023   3421000  1452.725766
1967 Zambia         Africa   47.768   3900000  1777.077318
1972 Zambia         Africa   50.107   4506497  1773.498265
1977 Zambia         Africa   51.386   5216550  1588.688299
1982 Zambia         Africa   51.821   6100407  1408.678565
1987 Zambia         Africa   50.821   7272406  1213.315116
1992 Zambia         Africa   46.100   8381163  1210.884633
1997 Zambia         Africa   40.238   9417789  1071.353818
2002 Zambia         Africa   39.193  10595811  1071.613938
2007 Zambia         Africa   42.384  11746035  1271.211593
1952 Zimbabwe       Africa   48.451   3080907   406.884115
1957 Zimbabwe       Africa   50.469   3646340   518.764268
1962 Zimbabwe       Africa   52.358   4277736   527.272182
1967 Zimbabwe       Africa   53.995   4995432   569.795071
1972 Zimbabwe       Africa   55.635   5861135   799.362176
1977 Zimbabwe       Africa   57.674   6642107   685.587682
1982 Zimbabwe       Africa   60.363   7636524   788.855041
1987 Zimbabwe       Africa   62.351   9216418   706.157306
1992 Zimbabwe       Africa   60.377  10704340   693.420786
1997 Zimbabwe       Africa   46.809  11404948   792.449960
2002 Zimbabwe       Africa   39.989  11926563   672.038623
2007 Zimbabwe       Africa   43.487  12311143   469.709298

[1704 rows x 4 columns]

In [35]:
df.sort_index(inplace=True)
df

                              continent  lifeExp        pop     gdpPercap
year country
1952 Afghanistan                   Asia   28.801    8425333    779.445314
     Albania                     Europe   55.230    1282697   1601.056136
     Algeria                     Africa   43.077    9279525   2449.008185
     Angola                      Africa   30.015    4232095   3520.610273
     Argentina                 Americas   62.485   17876956   5911.315053
     Australia                  Oceania   69.120    8691212  10039.595640
     Austria                     Europe   66.800    6927772   6137.076492
     Bahrain                       Asia   50.939     120447   9867.084765
     Bangladesh                    Asia   37.484   46886859    684.244172
     Belgium                     Europe   68.000    8730405   8343.105127
     Benin                       Africa   38.223    1738315   1062.752200
     Bolivia                   Americas   40.414    2883315   2677.326347
     Bosnia and Herzegovina      Europe   53.820    2791000    973.533195
     Botswana                    Africa   47.622     442308    851.241141
     Brazil                    Americas   50.917   56602560   2108.944355
     Bulgaria                    Europe   59.600    7274900   2444.286648
     Burkina Faso                Africa   31.975    4469979    543.255241
     Burundi                     Africa   39.031    2445618    339.296459
     Cambodia                      Asia   39.417    4693836    368.469286
     Cameroon                    Africa   38.523    5009067   1172.667655
     Canada                    Americas   68.750   14785584  11367.161120
     Central African Republic    Africa   35.463    1291695   1071.310713
     Chad                        Africa   38.092    2682462   1178.665927
     Chile                     Americas   54.745    6377619   3939.978789
     China                         Asia   44.000  556263527    400.448611
     Colombia                  Americas   50.643   12350771   2144.115096
     Comoros                     Africa   40.715     153936   1102.990936
     Congo, Dem. Rep.            Africa   39.143   14100005    780.542326
     Congo, Rep.                 Africa   42.111     854885   2125.621418
     Costa Rica                Americas   57.206     926317   2627.009471
...                                 ...      ...        ...           ...
2007 Sierra Leone                Africa   42.568    6144562    862.540756
     Singapore                     Asia   79.972    4553009  47143.179640
     Slovak Republic             Europe   74.663    5447502  18678.314350
     Slovenia                    Europe   77.926    2009245  25768.257590
     Somalia                     Africa   48.159    9118773    926.141068
     South Africa                Africa   49.339   43997828   9269.657808
     Spain                       Europe   80.941   40448191  28821.063700
     Sri Lanka                     Asia   72.396   20378239   3970.095407
     Sudan                       Africa   58.556   42292929   2602.394995
     Swaziland                   Africa   39.613    1133066   4513.480643
     Sweden                      Europe   80.884    9031088  33859.748350
     Switzerland                 Europe   81.701    7554661  37506.419070
     Syria                         Asia   74.143   19314747   4184.548089
     Taiwan                        Asia   78.400   23174294  28718.276840
     Tanzania                    Africa   52.517   38139640   1107.482182
     Thailand                      Asia   70.616   65068149   7458.396327
     Togo                        Africa   58.420    5701579    882.969944
     Trinidad and Tobago       Americas   69.819    1056608  18008.509240
     Tunisia                     Africa   73.923   10276158   7092.923025
     Turkey                      Europe   71.777   71158647   8458.276384
     Uganda                      Africa   51.542   29170398   1056.380121
     United Kingdom              Europe   79.425   60776238  33203.261280
     United States             Americas   78.242  301139947  42951.653090
     Uruguay                   Americas   76.384    3447496  10611.462990
     Venezuela                 Americas   73.747   26084662  11415.805690
     Vietnam                       Asia   74.249   85262356   2441.576404
     West Bank and Gaza            Asia   73.422    4018332   3025.349798
     Yemen, Rep.                   Asia   62.698   22211743   2280.769906
     Zambia                      Africa   42.384   11746035   1271.211593
     Zimbabwe                    Africa   43.487   12311143    469.709298

[1704 rows x 4 columns]

In [36]:
df.reset_index(inplace=True)
df

,year,country,continent,lifeExp,pop,gdpPercap
0,1952,Afghanistan,Asia,28.801,8425333,779.445314
1,1952,Albania,Europe,55.230,1282697,1601.056136
2,1952,Algeria,Africa,43.077,9279525,2449.008185
3,1952,Angola,Africa,30.015,4232095,3520.610273
4,1952,Argentina,Americas,62.485,17876956,5911.315053
5,1952,Australia,Oceania,69.120,8691212,10039.595640
6,1952,Austria,Europe,66.800,6927772,6137.076492
7,1952,Bahrain,Asia,50.939,120447,9867.084765
8,1952,Bangladesh,Asia,37.484,46886859,684.244172
9,1952,Belgium,Europe,68.000,8730405,8343.105127
10,1952,Benin,Africa,38.223,1738315,1062.752200
11,1952,Bolivia,Americas,40.414,2883315,2677.326347
12,1952,Bosnia and Herzegovina,Europe,53.820,2791000,973.533195
13,1952,Botswana,Africa,47.622,442308,851.241141
14,1952,Brazil,Americas,50.917,56602560,2108.944355
15,1952,Bulgaria,Europe,59.600,7274900,2444.286648
16,1952,Burkina Faso,Africa,31.975,4469979,543.255241
17,1952,Burundi,Africa,39.031,2445618,339.296459
18,1952,Cambodia,Asia,39.417,4693836,368.469286
19,1952,Cameroon,Africa,38.523,5009067,1172.667655
20,1952,Canada,Americas,68.750,14785584,11367.161120
21,1952,Central African Republic,Africa,35.463,1291695,1071.310713
22,1952,Chad,Africa,38.092,2682462,1178.665927
23,1952,Chile,Americas,54.745,6377619,3939.978789
24,1952,China,Asia,44.000,556263527,400.448611
25,1952,Colombia,Americas,50.643,12350771,2144.115096
26,1952,Comoros,Africa,40.715,153936,1102.990936
27,1952,"Congo, Dem. Rep.",Africa,39.143,14100005,780.542326
28,1952,"Congo, Rep.",Africa,42.111,854885,2125.621418
29,1952,Costa Rica,Americas,57.206,926317,2627.009471
...,...,...,...,...,...,...
1674,2007,Sierra Leone,Africa,42.568,6144562,862.540756
1675,2007,Singapore,Asia,79.972,4553009,47143.179640
1676,2007,Slovak Republic,Europe,74.663,5447502,18678.314350
1677,2007,Slovenia,Europe,77.926,2009245,25768.257590
1678,2007,Somalia,Africa,48.159,9118773,926.141068
1679,2007,South Africa,Africa,49.339,43997828,9269.657808
1680,2007,Spain,Europe,80.941,40448191,28821.063700
1681,2007,Sri Lanka,Asia,72.396,20378239,3970.095407
1682,2007,Sudan,Africa,58.556,42292929,2602.394995
1683,2007,Swaziland,Africa,39.613,1133066,4513.480643
1684,2007,Sweden,Europe,80.884,9031088,33859.748350
1685,2007,Switzerland,Europe,81.701,7554661,37506.419070
1686,2007,Syria,Asia,74.143,19314747,4184.548089
1687,2007,Taiwan,Asia,78.400,23174294,28718.276840
1688,2007,Tanzania,Africa,52.517,38139640,1107.482182
1689,2007,Thailand,Asia,70.616,65068149,7458.396327
1690,2007,Togo,Africa,58.420,5701579,882.969944
1691,2007,Trinidad and Tobago,Americas,69.819,1056608,18008.509240
1692,2007,Tunisia,Africa,73.923,10276158,7092.923025
1693,2007,Turkey,Europe,71.777,71158647,8458.276384
1694,2007,Uganda,Africa,51.542,29170398,1056.380121
1695,2007,United Kingdom,Europe,79.425,60776238,33203.261280
1696,2007,United States,Americas,78.242,301139947,42951.653090
1697,2007,Uruguay,Americas,76.384,3447496,10611.462990
1698,2007,Venezuela,Americas,73.747,26084662,11415.805690
1699,2007,Vietnam,Asia,74.249,85262356,2441.576404
1700,2007,West Bank and Gaza,Asia,73.422,4018332,3025.349798
1701,2007,"Yemen, Rep.",Asia,62.698,22211743,2280.769906
1702,2007,Zambia,Africa,42.384,11746035,1271.211593
1703,2007,Zimbabwe,Africa,43.487,12311143,469.709298

In [37]:
df.set_index(['country', 'year'], inplace=True)
df

                              continent  lifeExp        pop     gdpPercap
country                  year
Afghanistan              1952      Asia   28.801    8425333    779.445314
Albania                  1952    Europe   55.230    1282697   1601.056136
Algeria                  1952    Africa   43.077    9279525   2449.008185
Angola                   1952    Africa   30.015    4232095   3520.610273
Argentina                1952  Americas   62.485   17876956   5911.315053
Australia                1952   Oceania   69.120    8691212  10039.595640
Austria                  1952    Europe   66.800    6927772   6137.076492
Bahrain                  1952      Asia   50.939     120447   9867.084765
Bangladesh               1952      Asia   37.484   46886859    684.244172
Belgium                  1952    Europe   68.000    8730405   8343.105127
Benin                    1952    Africa   38.223    1738315   1062.752200
Bolivia                  1952  Americas   40.414    2883315   2677.326347
Bosnia and Herzegovina   1952    Europe   53.820    2791000    973.533195
Botswana                 1952    Africa   47.622     442308    851.241141
Brazil                   1952  Americas   50.917   56602560   2108.944355
Bulgaria                 1952    Europe   59.600    7274900   2444.286648
Burkina Faso             1952    Africa   31.975    4469979    543.255241
Burundi                  1952    Africa   39.031    2445618    339.296459
Cambodia                 1952      Asia   39.417    4693836    368.469286
Cameroon                 1952    Africa   38.523    5009067   1172.667655
Canada                   1952  Americas   68.750   14785584  11367.161120
Central African Republic 1952    Africa   35.463    1291695   1071.310713
Chad                     1952    Africa   38.092    2682462   1178.665927
Chile                    1952  Americas   54.745    6377619   3939.978789
China                    1952      Asia   44.000  556263527    400.448611
Colombia                 1952  Americas   50.643   12350771   2144.115096
Comoros                  1952    Africa   40.715     153936   1102.990936
Congo, Dem. Rep.         1952    Africa   39.143   14100005    780.542326
Congo, Rep.              1952    Africa   42.111     854885   2125.621418
Costa Rica               1952  Americas   57.206     926317   2627.009471
...                                 ...      ...        ...           ...
Sierra Leone             2007    Africa   42.568    6144562    862.540756
Singapore                2007      Asia   79.972    4553009  47143.179640
Slovak Republic          2007    Europe   74.663    5447502  18678.314350
Slovenia                 2007    Europe   77.926    2009245  25768.257590
Somalia                  2007    Africa   48.159    9118773    926.141068
South Africa             2007    Africa   49.339   43997828   9269.657808
Spain                    2007    Europe   80.941   40448191  28821.063700
Sri Lanka                2007      Asia   72.396   20378239   3970.095407
Sudan                    2007    Africa   58.556   42292929   2602.394995
Swaziland                2007    Africa   39.613    1133066   4513.480643
Sweden                   2007    Europe   80.884    9031088  33859.748350
Switzerland              2007    Europe   81.701    7554661  37506.419070
Syria                    2007      Asia   74.143   19314747   4184.548089
Taiwan                   2007      Asia   78.400   23174294  28718.276840
Tanzania                 2007    Africa   52.517   38139640   1107.482182
Thailand                 2007      Asia   70.616   65068149   7458.396327
Togo                     2007    Africa   58.420    5701579    882.969944
Trinidad and Tobago      2007  Americas   69.819    1056608  18008.509240
Tunisia                  2007    Africa   73.923   10276158   7092.923025
Turkey                   2007    Europe   71.777   71158647   8458.276384
Uganda                   2007    Africa   51.542   29170398   1056.380121
United Kingdom           2007    Europe   79.425   60776238  33203.261280
United States            2007  Americas   78.242  301139947  42951.653090
Uruguay                  2007  Americas   76.384    3447496  10611.462990
Venezuela                2007  Americas   73.747   26084662  11415.805690
Vietnam                  2007      Asia   74.249   85262356   2441.576404
West Bank and Gaza       2007      Asia   73.422    4018332   3025.349798
Yemen, Rep.              2007      Asia   62.698   22211743   2280.769906
Zambia                   2007    Africa   42.384   11746035   1271.211593
Zimbabwe                 2007    Africa   43.487   12311143    469.709298

[1704 rows x 4 columns]

In [38]:
df.sort_index(inplace=True)
df

                 continent  lifeExp       pop    gdpPercap
country     year
Afghanistan 1952      Asia   28.801   8425333   779.445314
            1957      Asia   30.332   9240934   820.853030
            1962      Asia   31.997  10267083   853.100710
            1967      Asia   34.020  11537966   836.197138
            1972      Asia   36.088  13079460   739.981106
            1977      Asia   38.438  14880372   786.113360
            1982      Asia   39.854  12881816   978.011439
            1987      Asia   40.822  13867957   852.395945
            1992      Asia   41.674  16317921   649.341395
            1997      Asia   41.763  22227415   635.341351
            2002      Asia   42.129  25268405   726.734055
            2007      Asia   43.828  31889923   974.580338
Albania     1952    Europe   55.230   1282697  1601.056136
            1957    Europe   59.280   1476505  1942.284244
            1962    Europe   64.820   1728137  2312.888958
            1967    Europe   66.220   1984060  2760.196931
            1972    Europe   67.690   2263554  3313.422188
            1977    Europe   68.930   2509048  3533.003910
            1982    Europe   70.420   2780097  3630.880722
            1987    Europe   72.000   3075321  3738.932735
            1992    Europe   71.581   3326498  2497.437901
            1997    Europe   72.950   3428038  3193.054604
            2002    Europe   75.651   3508512  4604.211737
            2007    Europe   76.423   3600523  5937.029526
Algeria     1952    Africa   43.077   9279525  2449.008185
            1957    Africa   45.685  10270856  3013.976023
            1962    Africa   48.303  11000948  2550.816880
            1967    Africa   51.407  12760499  3246.991771
            1972    Africa   54.518  14760787  4182.663766
            1977    Africa   58.014  17152804  4910.416756
...                    ...      ...       ...          ...
Yemen, Rep. 1982      Asia   49.113   9657618  1977.557010
            1987      Asia   52.922  11219340  1971.741538
            1992      Asia   55.599  13367997  1879.496673
            1997      Asia   58.020  15826497  2117.484526
            2002      Asia   60.308  18701257  2234.820827
            2007      Asia   62.698  22211743  2280.769906
Zambia      1952    Africa   42.038   2672000  1147.388831
            1957    Africa   44.077   3016000  1311.956766
            1962    Africa   46.023   3421000  1452.725766
            1967    Africa   47.768   3900000  1777.077318
            1972    Africa   50.107   4506497  1773.498265
            1977    Africa   51.386   5216550  1588.688299
            1982    Africa   51.821   6100407  1408.678565
            1987    Africa   50.821   7272406  1213.315116
            1992    Africa   46.100   8381163  1210.884633
            1997    Africa   40.238   9417789  1071.353818
            2002    Africa   39.193  10595811  1071.613938
            2007    Africa   42.384  11746035  1271.211593
Zimbabwe    1952    Africa   48.451   3080907   406.884115
            1957    Africa   50.469   3646340   518.764268
            1962    Africa   52.358   4277736   527.272182
            1967    Africa   53.995   4995432   569.795071
            1972    Africa   55.635   5861135   799.362176
            1977    Africa   57.674   6642107   685.587682
            1982    Africa   60.363   7636524   788.855041
            1987    Africa   62.351   9216418   706.157306
            1992    Africa   60.377  10704340   693.420786
            1997    Africa   46.809  11404948   792.449960
            2002    Africa   39.989  11926563   672.038623
            2007    Africa   43.487  12311143   469.709298

[1704 rows x 4 columns]

In [44]:
df.loc['Japan', ['pop','lifeExp']]

            pop  lifeExp
year
1952   86459025   63.030
1957   91563009   65.500
1962   95831757   68.730
1967  100825279   71.430
1972  107188273   73.420
1977  113872473   75.380
1982  118454974   77.110
1987  122091325   78.670
1992  124329269   79.360
1997  125956499   80.690
2002  127065841   82.000
2007  127467972   82.603

In [45]:
df.index.nlevels

2

In [47]:
df.index.levels

FrozenList([['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium', 'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', 'Cote d'Ivoire', 'Croatia', 'Cuba', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti', 'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.', 'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania', 'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Paraguay', ...], [1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002, 2007]])

In [52]:
df.loc[('Japan',1997)]

continent         Asia
lifeExp          80.69
pop          125956499
gdpPercap      28816.6
Name: (Japan, 1997), dtype: object

In [55]:
df.loc['Japan'].loc[1997:2007]

     continent  lifeExp        pop    gdpPercap
year
1997      Asia   80.690  125956499  28816.58499
2002      Asia   82.000  127065841  28604.59190
2007      Asia   82.603  127467972  31656.06806

In [60]:
df.loc['A':'D']                   #เอาตัวอักษร A- C

                    continent  lifeExp       pop     gdpPercap
country        year
Afghanistan    1952      Asia   28.801   8425333    779.445314
               1957      Asia   30.332   9240934    820.853030
               1962      Asia   31.997  10267083    853.100710
               1967      Asia   34.020  11537966    836.197138
               1972      Asia   36.088  13079460    739.981106
               1977      Asia   38.438  14880372    786.113360
               1982      Asia   39.854  12881816    978.011439
               1987      Asia   40.822  13867957    852.395945
               1992      Asia   41.674  16317921    649.341395
               1997      Asia   41.763  22227415    635.341351
               2002      Asia   42.129  25268405    726.734055
               2007      Asia   43.828  31889923    974.580338
Albania        1952    Europe   55.230   1282697   1601.056136
               1957    Europe   59.280   1476505   1942.284244
               1962    Europe   64.820   1728137   2312.888958
               1967    Europe   66.220   1984060   2760.196931
               1972    Europe   67.690   2263554   3313.422188
               1977    Europe   68.930   2509048   3533.003910
               1982    Europe   70.420   2780097   3630.880722
               1987    Europe   72.000   3075321   3738.932735
               1992    Europe   71.581   3326498   2497.437901
               1997    Europe   72.950   3428038   3193.054604
               2002    Europe   75.651   3508512   4604.211737
               2007    Europe   76.423   3600523   5937.029526
Algeria        1952    Africa   43.077   9279525   2449.008185
               1957    Africa   45.685  10270856   3013.976023
               1962    Africa   48.303  11000948   2550.816880
               1967    Africa   51.407  12760499   3246.991771
               1972    Africa   54.518  14760787   4182.663766
               1977    Africa   58.014  17152804   4910.416756
...                       ...      ...       ...           ...
Croatia        1982    Europe   70.460   4413368  13221.821840
               1987    Europe   71.520   4484310  13822.583940
               1992    Europe   72.527   4494013   8447.794873
               1997    Europe   73.680   4444595   9875.604515
               2002    Europe   74.876   4481020  11628.388950
               2007    Europe   75.748   4493312  14619.222720
Cuba           1952  Americas   59.421   6007797   5586.538780
               1957  Americas   62.325   6640752   6092.174359
               1962  Americas   65.246   7254373   5180.755910
               1967  Americas   68.290   8139332   5690.268015
               1972  Americas   70.723   8831348   5305.445256
               1977  Americas   72.649   9537988   6380.494966
               1982  Americas   73.717   9789224   7316.918107
               1987  Americas   74.174  10239839   7532.924763
               1992  Americas   74.414  10723260   5592.843963
               1997  Americas   76.151  10983007   5431.990415
               2002  Americas   77.158  11226999   6340.646683
               2007  Americas   78.273  11416987   8948.102923
Czech Republic 1952    Europe   66.870   9125183   6876.140250
               1957    Europe   69.030   9513758   8256.343918
               1962    Europe   69.900   9620282  10136.867130
               1967    Europe   70.380   9835109  11399.444890
               1972    Europe   70.290   9862158  13108.453600
               1977    Europe   70.710  10161915  14800.160620
               1982    Europe   70.960  10303704  15377.228550
               1987    Europe   71.580  10311597  16310.443400
               1992    Europe   72.400  10315702  14297.021220
               1997    Europe   74.010  10300707  16048.514240
               2002    Europe   75.510  10256295  17596.210220
               2007    Europe   76.486  10228744  22833.308510

[408 rows x 4 columns]