In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://github.com/prasertcbs/tutorial/raw/master/msleep.csv', nrows=10)
df

,name,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt,bodywt
0,Cheetah,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN,50.000
1,Owl monkey,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550,0.480
2,Mountain beaver,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN,1.350
3,Greater short-tailed shrew,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029,0.019
4,Cow,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300,600.000
5,Three-toed sloth,Bradypus,herbi,Pilosa,NaN,14.4,2.2,0.766667,9.6,NaN,3.850
6,Northern fur seal,Callorhinus,carni,Carnivora,vu,8.7,1.4,0.383333,15.3,NaN,20.490
7,Vesper mouse,Calomys,NaN,Rodentia,NaN,7.0,NaN,NaN,17.0,NaN,0.045
8,Dog,Canis,carni,Carnivora,domesticated,10.1,2.9,0.333333,13.9,0.07000,14.000
9,Roe deer,Capreolus,herbi,Artiodactyla,lc,3.0,NaN,NaN,21.0,0.09820,14.800

In [3]:
def hilight_font(e):
    color = 'red' if e > 10 else 'black'
    return f'color : {color}'

In [5]:
hilight_font(11)

'color : red'

In [9]:
df.style.applymap(hilight_font, subset = ['sleep_total'])

In [17]:
def hilight_bg(e):
    return 'background-color: yellow' if e > 10 else ''

In [18]:
df.style.applymap(hilight_bg, subset=['sleep_total'])

In [19]:
df.style.applymap(lambda e: f'background-color:deepskyblue' if e > 10 else '', subset=['awake'])

In [34]:
def upfont (e ,v):
    if e > v :
        style= 'font-size: 150%; background-color:deepskyblue; color:red; border: 3px solid yellow'
    else:
        style=''
    return style

In [35]:
df.style.applymap(upfont, v=10, subset=['sleep_total'])

In [41]:
df.style.applymap(lambda e: 'background-color:deepskyblue; color:red; font-size:130%; border: 3px solid blue' if e>10 else '',
                 subset=['sleep_total'])

In [45]:
df.style.applymap(lambda e: 'background-color:tan'if e=='herbi'else '', subset=['vore']).applymap(lambda e: 'background-color:deepskyblue; color:red; font-size:130%; border: 3px solid blue' if e>10 else '',
                 subset=['sleep_total'])